---
abstract: 'The great new Sentry!'
author:
  - 'Lenz Gschwendtner, C<< <norbu09 at cpan.org> >>'
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sentry
no_index:
  directory:
    - inc
    - t
requires:
  Config::GitLike: 0
  IO::Socket: 0
  LWP::UserAgent: 0
  Mouse: 0
  Mouse::Role: 0
  MouseX::Object::Pluggable: 0
  Sys::Hostname: 0
  Time::HiRes: 0
  URI::Escape: 0
  XML::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
